# Generated by Django 2.0.2 on 2018-02-12 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.TimeStampedModel')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(54054), django.core.validators.MinValueValidator(0)])),
                ('record_date', models.DateField(verbose_name='Date')),
                ('record_time', models.TimeField(verbose_name='Time')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('pages.timestampedmodel',),
        ),
    ]
