# Generated by Django 2.0.2 on 2018-02-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180213_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='timestampedmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
