# Generated by Django 2.0.2 on 2018-02-24 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(54054), django.core.validators.MinValueValidator(0)]),
        ),
    ]
