# Generated by Django 2.0.2 on 2018-02-27 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180227_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(default=datetime.time(14, 56, 38, 386331), verbose_name='Time'),
        ),
    ]
