# Generated by Django 2.0.2 on 2018-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180227_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='record_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
