# Generated by Django 2.0.2 on 2018-03-10 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180228_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_date',
            field=models.DateField(default=datetime.date(2018, 3, 10), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(auto_now_add=datetime.time(16, 52, 31, 207340), verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='substance',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
            preserve_default=False,
        ),
    ]
