# Generated by Django 2.0.2 on 2018-03-10 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20180311_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(auto_now_add=datetime.time(16, 56, 40, 541342), verbose_name='Time'),
        ),
    ]
