# Generated by Django 2.0.2 on 2018-03-11 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20180311_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='record_date',
            field=models.DateField(default=datetime.date(2018, 3, 11), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(default=datetime.time(8, 6, 43, 391490), verbose_name='Time'),
        ),
    ]
