# Generated by Django 2.0.2 on 2018-03-11 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20180311_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='record_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(default=datetime.date.today, verbose_name='Time'),
        ),
    ]
