# Generated by Django 2.0.2 on 2018-03-11 08:41

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20180311_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='record_date',
            field=models.DateField(default=backend.models.get_current_date, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='record_time',
            field=models.TimeField(default=backend.models.get_current_time, verbose_name='Time'),
        ),
    ]
